name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - nightly
    steps:
      - uses: actions/checkout@v4
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - name: Build (default features)
        run: cargo build --verbose
      - name: Build (nightly)
        if: matrix.toolchain == 'nightly'
        run: cargo build --all-features --verbose
      - name: Tests
        run: cargo test --verbose
      - name: Clippy (all features)
        if: matrix.toolchain == 'nightly'
        run: cargo clippy --all-features -- -D warnings
      - name: Clippy (default features)
        if: matrix.toolchain != 'nightly'
        run: cargo clippy -- -D warnings
